site_name: PaulistringsQuantumCircuitSimulations
theme:
    name: material
    palette:
        primary: white
        accent: blue
    features:
        - navigation.tabs
nav:
    - Home: index.md
    - api.md
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Ryo-wtnb11/PauliStringsQuantumCircuitSimulations
plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  options:
                      heading_level: 3
                      show_root_toc_entry: true
                      docstring_section_style: list
                      show_source: true

extra_javascript:
    - js/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
